### PR TITLE
Include PHP 8 compatibility.

### PR DESCRIPTION
**Pull request by mikebronner**

### CODE REVIEW

**Comment by mikebronner** [comment]
I don't believe any other work is needed, I have been trialing it for the past several days, and it works great.

**Comment by tom-pryor** [comment]
Presumably this also requires #87 ?

**Comment by mikebronner** [comment]
@tom-pryor I was able to run it without requiring any other dependency updates.

**Comment by mikebronner** [comment]
Closing this, as this appears to be resolved now.

**Pull request closed without merging**
