### PR TITLE
Sum cache

### PR DESCRIPTION
**Pull request by cviebrock**
Implements the SumCache idea mentioned in #34. :smile:

### CODE REVIEW

**Comment by cviebrock** [comment]
So, I'm not sure why the tests are failing.  If I run each set of tests individually, they both pass:

```sh
./vendor/bin/phpunit ./tests/Acceptance
./vendor/bin/phpunit ./tests/Unit
```

Any ideas?

**Comment by kirkbushell** [comment]
Thanks for this work. I feel however that some of the language isn't quite right, due to the fact that it was copied from count cache. For example, I do not think increment/decrement works in this context. Perhaps increase/decrease, or something else?

**Comment by kirkbushell** [comment]
As for the tests, I'll check them out later today. Feeling much better but I have work to do :)

**Comment by cviebrock** [comment]
Fair enough ... I will review the language and see if I can make it more applicable.  I'll also adjust the PR to accept the "explicit" style configuration from my other PR.

**Comment by kirkbushell** [comment]
Cool okay, np.

**Comment by cviebrock** [comment]
Renamed some methods, updated tests, and added new tests for explicit config syntax.

Full test suite still fails, but they pass if you run the Unit and Acceptance tests separately.

I leave it to you now.  ;)

**Comment by kirkbushell** [comment]
I get a different problem, as it's not setting up the connection properly.

**Comment by kirkbushell** [comment]
I've fixed up these tests and merged in the resulting fixes. Pretty cool github actually recognised that I pulled down your branch locally and had worked on it then pushed it here. Nice :)

There's still a bit of testing to be done I feel regarding this work and a few other PRs that have come in recently. Plus I'm addressing some issues I have with the API, in addition to improving the usability of the library, so a 1.5 release is still a ways off.

**Comment by cviebrock** [comment]
No problem, thanks!  This is going to be super-helpful for my current project ... which is usually why I make PRs. ;)

**Pull request merged**
