### PR TITLE
feat: add "where" config option to cacheable

### PR DESCRIPTION
**Pull request by jaulz**

### CODE REVIEW

**Comment by kirkbushell** [comment]
Can I get a squash on those commits? Repeated commit messages are not great for commit history.

**Comment by jaulz** [comment]
@kirkbushell sure, here you go 😊

**Review by kirkbushell — CHANGES_REQUESTED** [review]
Need to add tests to cover the new features.

**Comment by jaulz** [comment]
Yep, will work on it 😊

**Comment by jaulz** [comment]
@kirkbushell I just extended the tests and the README. Could you please check it?

**Comment by jaulz** [comment]
For anyone interested in this, I forked the repository and extended the conditions to even support not equal etc.:
https://github.com/jaulz/eloquence/

@kirkbushell let me know in case you want it to be part of this package.

**Comment by kirkbushell** [comment]
> For anyone interested in this, I forked the repository and extended the conditions to even support not equal etc.:
> https://github.com/jaulz/eloquence/
> 
> @kirkbushell let me know in case you want it to be part of this package.

Yup, will do - just been a bit hectic of late.

**Comment by kirkbushell** [comment]
I'm looking at changing how this functions in 11.0. Instead of using array syntax, looking at a better approach, potentially a template pattern where you can define any clauses you need.

I'm also moving away from using DB, as it's now better handled using transactions.

**Pull request closed without merging**
